### ISSUE TITLE
ListOptionsContracts ignores `polygonModels.GT` and `polygonModels.GTE`

### ISSUE THREAD

**Issue by lijunsong** [polygon-io/client-go#167]
**Describe the bug**
ListOptionsContracts does not respect the strike price params settings.

**To Reproduce**
```
	asOf, _ := time.Parse(time.RFC3339, "2022-07-14T09:45:00-04:00")
	expr, _ := time.Parse(time.RFC3339, "2022-07-15T00:00:00-04:00")
	params := polygonModels.ListOptionsContractsParams{}.
		WithAsOf(polygonModels.Date(asOf)).
		WithExpirationDate(polygonModels.EQ, polygonModels.Date(expr)).
		WithUnderlyingTicker(polygonModels.EQ, string("AAPL")).
		WithStrikePrice(polygonModels.GT, 136).
		WithContractType("put")
	fmt.Printf("%v\n", *params.StrikePriceGT)
	iter := polygonClient.ListOptionsContracts(context.Background(), params)
	for iter.Next() {
		fmt.Printf("%s\n", iter.Item().Ticker)
	}
```

**Expected behavior**
client should return put contracts with strikes greater than 136, but the program returns everything starting from strke 50
```
$ go run main.go 
136
O:AAPL220715P00050000
O:AAPL220715P00055000
O:AAPL220715P00060000
O:AAPL220715P00065000
O:AAPL220715P00070000
O:AAPL220715P00075000
O:AAPL220715P00080000
O:AAPL220715P00085000
O:AAPL220715P00090000
...
```

**Screenshots**
not needed

**Additional context**
1. more testing shows `polygonModels.LT` and `polygonModels.LTE` work as expected.
2. version `github.com/polygon-io/client-go v1.1.0`

**Comment by lijunsong** [comment]
Sigh, I find out the issue: https://github.com/polygon-io/client-go/blob/9b34d0cf21f035eb1b24e604dd4f7c8ef743932b/rest/models/contracts.go#L49-L50

```
StrikePriceGT  *float64 `query:"strike_price.GT"`
StrikePriceGTE *float64 `query:"strike_price.GTE"`
```
Shouldn't be uppercase. Same for ExpirationDateGTE, and UnderlyingTickerGTE. (cc @Darcy-Linde Your commit https://github.com/polygon-io/client-go/commit/b71c8b21915bdc82ba9b1c369b82978c98819451)

After I calling QueryParam the problem is gone.

**Comment by morningvera** [comment]
hey @lijunsong, thanks for the detailed bug report! just opened a PR with a fix for this and will have that merged and released soon. if you still have trouble with it, feel free to reopen this issue.
