### ISSUE TITLE
Unmarshal error when running the example code (GetAllTickersSnapshot)

### ISSUE THREAD

**Issue by nlalor** [polygon-io/client-go#224]
**Describe the bug**

`GetAllTickersSnapshot` fails to unmarshal the `AccumulatedVolume` value on `MinuteSnapshot`.

`2023/01/06 09:29:47.837606 ERROR RESTY json: cannot unmarshal number 1.012021e+06 into Go struct field MinuteSnapshot.tickers.min.av of type int, Attempt 1
2023/01/06 09:29:47 failed to execute request: json: cannot unmarshal number 1.012021e+06 into Go struct field MinuteSnapshot.tickers.min.av of type int`

**To Reproduce**

Run the example code shown in the "Using the Client" section of the readme. No changes to the example code are needed to reproduce the error on my end.

**Expected behavior**

`GetAllTickersSnapshot` should correctly handle the accumulated volume data.

**Screenshots**

**Additional context**

Go version 1.19

I was able to "fix" this error locally by changing the data type for the `AccumulatedValue` field to `float64` instead of `int`.
Not sure if the schema is just out of date or if there may be some versioning issue.

**Comment by antdjohns** [comment]
Hey @nlalor, We were able to reproduce the issue. Thank you for bringing it to our attention.

**Comment by morningvera** [comment]
This was closed by #230. Thanks for the bug report @nlalor and for the fix @antdjohns!
