### ISSUE TITLE
Ticker Events Endpoint

### ISSUE THREAD

**Issue by nathanhack** [polygon-io/client-go#225]
**Is your feature request related to a problem? Please describe.**
The client is missing the Event Endpoint (/vX/reference/tickers/{id}/events).

**Describe the solution you'd like**
Ideally there would be a function added to the client for the endpoint.

**Comment by jbonzo** [comment]
@nathanhack Great callout, we will implement this missing endpoint soon.

**Comment by jbonzo** [comment]
Implemented and released as `v1.8.0`
