### ISSUE TITLE
Dividend Date as time.Time

### ISSUE THREAD

**Issue by nathanhack** [polygon-io/client-go#232]
**Is your feature request related to a problem? Please describe.**
The date values from the ListDividend() should be `time.Time` not `string`'s. Similar to your other APIs like GetAgg()

**Describe the solution you'd like**
It would be amazing if the type was change from a `string` to `time.Time`.

**Comment by antdjohns** [comment]
@nathanhack thanks for bringing this to our attention. I’m taking note and we will review to see if this change in necessary.
Only issue I see with a type change in this circumstance is that it would be a breaking change and possibly require multiple changes for some end users.

**Comment by morningvera** [comment]
@nathanhack I think this makes sense and I'm seeing a few other cases where we could use our time aliases as well. I'll discuss it with the team and merge this change if we decide to allow the breaking change. Thanks for the request!

**Comment by morningvera** [comment]
Closed by #248 and released in `v1.10.0`. Thanks again for bringing this issue up @nathanhack!
