### ISSUE TITLE
Rest client ListTrades() doesn't respect params

### ISSUE THREAD

**Issue by YouriT** [polygon-io/client-go#238]
**Describe the bug**

When using timestampGTE & timestampLTE with a time that ends with 0h 0m 0s 0ns, the API query is not generated properly.

**To Reproduce**

```go
tz, _ := time.LoadLocation("America/New_York")
from := time.Date(2023, 1, 15, 0, 0, 0, 0, tz)
to := time.Date(2023, 1, 20, 0, 0, 0, 0, tz)
fromTS := models.Nanos(from)
toTS := models.Nanos(to)
iter := c.ListTrades(context.TODO(), &models.ListTradesParams{
	Ticker:       symbol,
	TimestampGTE: &fromTS,
	TimestampLTE: &toTS,
	Limit:        &limit,
	Order:        &order,
	Sort:         &sort,
}, models.APIKey(config.POLYGON_TOKEN))
```

**Expected behavior**

the iterator should return trades from the 19th until the 20th at midnight.

**Screenshots**

<img width="896" alt="Screenshot 2023-01-29 at 15 39 16" src="https://user-images.githubusercontent.com/1449797/215333751-4618a5d3-addb-4cad-9852-2b0a96b2f62b.png">

**Additional context**

Issue comes from the assumption made [here](https://github.com/polygon-io/client-go/blob/40baa9507128a5057bccb74a58c96b549fa5088d/rest/encoder/encoder.go#L99-L115) that if the time provided by the user trails with zero, it means that the user wants to send the date to the API.

**Comment by antdjohns** [comment]
Hey @YouriT,
Thanks for bringing this up. I was not able to recreate the issue. 

#### Nasdaq trading hrs are as follows:
- Pre-market: 4am EST-9:30 EST 
- Intraday: 9:30 EST - 4:00PM EST
- After-hours: 4:00PM EST - 8:00PM EST
*some brokerages offer different trading hours.

It is possible that given the range your request surpassed the 50_000 limit. 

*note: timestamps are PST AND the 16th was a holiday (no trading) Martin Luther King Jr. Day
#### Timestamps Order Ascending:
2023-01-17 04:00:02.358346923 -0800 PST
2023-01-17 04:33:53.641652721 -0800 PST
2023-01-17 06:29:59.956693178 -0800 PST
2023-01-17 06:30:01.042222789 -0800 PST
2023-01-17 06:30:01.042227558 -0800 PST



#### Timestamps Order Descending:
2023-01-20 14:52:00.669310725 -0800 PST
2023-01-20 13:24:11.29306308 -0800 PST
2023-01-20 13:14:59.035721186 -0800 PST
2023-01-20 13:14:59.035702036 -0800 PST
2023-01-20 13:07:36.270063571 -0800 PST

Code to reproduce
```golang
package main

import (
	"fmt"
	polygon "github.com/polygon-io/client-go/rest"
	"github.com/polygon-io/client-go/rest/models"
	"github.com/polygon-io/ptime"
	"log"
	"time"
)

func main() {
	c := polygon.New("<API_KEY>")
	from := time.Date(2023, 1, 16, 0, 0, 0, 0, ptime.NewYorkTime) 
	to := time.Date(2023, 1, 20, 0, 0, 0, 0, ptime.NewYorkTime)
	fromTS := models.Nanos(from)
	toTS := models.Nanos(to)
	s := "NTAP"
	l := 1
	o := models.Order("desc")
	iter := c.ListTrades(context.TODO(), &models.ListTradesParams{
		Ticker:       s,
		TimestampGTE: &fromTS,
		TimestampLTE:  &toTS,
		Limit:                   &l,
		Order:                 &o,
	})

	for iter.Next() {
		fmt.Println(time.Time(iter.Item().SipTimestamp)) // do something with the current value
	}

	if iter.Err() != nil {
		log.Fatal(iter.Err())
	}
}
```

**Comment by YouriT** [comment]
Hi @antdjohns, well your repro actually shows the issue perfectly.

You wrote `to := time.Date(2023, 1, 20, 0, 0, 0, 0, ptime.NewYorkTime)` meaning you're not expecting trades > `2023-01-20T00:00:00.000-05:00` but in your response last trade you are receiving is at `2023-01-20 14:52:00.669310725 -0800 PST` which is greater than the `TimestampLTE` param of your request.

```go
tz, _ := time.LoadLocation("America/New_York")
limit := time.Date(2023, 1, 20, 0, 0, 0, 0, tz)
lastTrade := "2023-01-20T14:52:00.669-08:00"
t, _ := time.Parse(time.RFC3339Nano, lastTrade)
if t.After(limit) {
    panic("last trade is after TimestampLTE")
}
```

**Comment by antdjohns** [comment]
I see. 

We will look into this. 

For now assume that LTE for a date is inclusive when set to zero hour.

**Comment by YouriT** [comment]
Switched to LT to temporarily solve my issue, does the trick in my case

**Comment by antdjohns** [comment]
Excellent!

Closing ticket.

**Comment by YouriT** [comment]
Doesn't change the fact there is a bug in the lib. I even pointed out where. Why closing the issue?
