### ISSUE TITLE
Ticker ListDate returns different than expected

### ISSUE THREAD

**Issue by nathanhack** [polygon-io/client-go#241]
Maybe this isn't a Bug, but I consider this a consistency thing.  

The Agg interface returns daily values with dates/time that is set for EST (this is what I would expect).

I would also expect the same for the Ticker, but it doesn't. Instead it returns a value that is UTC.

Since the stocks are based in the US I would have expected to see to see those also be EST.

**Comment by justinpolygon** [comment]
Hey @nathanhack, do you happen to have the code snippets you were using? I've looked around and cannot reproduce this and I don't actually see anything related to timezones so I'm wondering if it was coming from the API itself. If you still happen to have this please let me know and I'll dig a little further.

**Comment by justinpolygon** [comment]
I'm going to close as not reproducible for now. If you find the code or are still having the issue please let me know and I'll check it out.
