### ISSUE TITLE
ListArgs does not work with Millis

### ISSUE THREAD

**Issue by b26** [polygon-io/client-go#312]
**Describe the bug**

**To Reproduce**

1. Use this sample code

```golang
func TestCandleStickData(t *testing.T) {
	contract := "SPXW230703P04450000"

	client := polygon.New(api_key)

	date, _ := time.Parse("2006-01-02", "2023-07-03")

	from := models.Millis(date)

	to := models.Millis(date)

	order := models.Asc

	limit := 120

	adjusted := false

	var candles []models.Agg

	items := client.ListAggs(context.Background(), &models.ListAggsParams{
		Ticker:     fmt.Sprintf("O:%v", contract),
		Multiplier: 5,
		From:       from,
		To:         to,
		Order:      &order,
		Limit:      &limit,
		Timespan:   models.Minute,
		Adjusted:   &adjusted,
	})

	for {
		if items.Next() == false {
			break
		}

		candles = append(candles, items.Item())
	}

	if len(candles) == 0 {
		t.Error("No candles found")
		t.FailNow()
	}
}
```

2. Set a breakpoint in https://github.com/polygon-io/client-go/blob/master/rest/client/client.go#L79
3. Go back to your test method and click `"Debug Test"`
4. inspect the URI `"/v2/aggs/ticker/O:SPXW230703P04450000/range/5/minute/1688342400000/1688342400000?adjusted=false&limit=120&sort=asc"`

These values `1688342400000/1688342400000` are incorrect

**Expected behavior**

The expected generated URL should be `https://api.polygon.io/v2/aggs/ticker/O:SPXW230703P04450000/range/5/minute/2023-07-03/2023-07-03?adjusted=false&sort=asc&limit=120`

So instead of  `1688342400000/1688342400000` it should be `2023-07-03`

The documentation for `"ListAggsParams"` says that `Millis` can be either a timestamp or `YYYY-MM-DD` however the struct only supports the type `"Millis"`

Also the URI that https://polygon.io/docs/options/get_v2_aggs_ticker__optionsticker__range__multiplier___timespan___from___to

generates is the expected URI. 

**Screenshots**

Screenshot of debugger uri

![image](https://github.com/polygon-io/client-go/assets/2287343/f5cd321c-f49e-480a-a824-4f92e238d8c8)

Screenshot of `items` that is return by `ListArggs` shows no errors and no results

![image](https://github.com/polygon-io/client-go/assets/2287343/576eafe4-6e20-49ac-bca0-34c1c3118509)

I'm not blocked by this at all. I can just change 

```
type ListAggsParams struct { 
  From Millis -> From string
  To Millis -> To string
}
```

For example, this fixes the issue 

```golang
type ListAggsParams struct {
	// The ticker symbol of the stock/equity.
	Ticker string `validate:"required" path:"ticker"`

	// The size of the timespan multiplier.
	Multiplier int `validate:"required" path:"multiplier"`

	// The size of the time window.
	Timespan Timespan `validate:"required" path:"timespan"`

	// The start of the aggregate time window. Either a date with the format YYYY-MM-DD or a millisecond timestamp.
	From string `validate:"required" path:"from"`

	// The end of the aggregate time window. Either a date with the format YYYY-MM-DD or a millisecond timestamp.
	To string `validate:"required" path:"to"`

	// Whether or not the results are adjusted for splits. By default, results are adjusted. Set this to false to get
	// results that are NOT adjusted for splits.
	Adjusted *bool `query:"adjusted"`

	// Order the results by timestamp. asc will return results in ascending order (oldest at the top), desc will return
	// results in descending order (newest at the top).
	Order *Order `query:"sort"`

	// Limits the number of base aggregates queried to create the aggregate results. Max 50000 and Default 5000. Read
	// more about how limit is used to calculate aggregate results in our article on Aggregate Data API Improvements:
	// https://polygon.io/blog/aggs-api-updates/.
	Limit *int `query:"limit"`
}
```

Notice how I changed `"From"` from using `"Millis"` to a `"string"`

Cheers

**Comment by justinpolygon** [comment]
Hey @b26, the API can accept both YYYY-MM-DD and unixtime as date formats. I think there might have been a bug in your test script because that your contact was set to `SPXW230703P04450000` and probably needed to be `O:SPXW230703P04450000`. That's expired now so I'm not able to reproduce on that one though. Then, in the second example you mentioned `O:SPXW230703P04450000`. So, I suspect it was just the missing `O:`.

Either way, the API should work with both unixtime and regular dates.

Here's an example script:

```go
package main

import (
	"context"
	"log"
	"os"
	"time"

	polygon "github.com/polygon-io/client-go/rest"
	"github.com/polygon-io/client-go/rest/models"
)

func main() {

	// init client
	c := polygon.New(os.Getenv("POLYGON_API_KEY"))

	// set params
	params := models.ListAggsParams{
		Ticker:     "O:SPY251219C00650000",
		Multiplier: 5,
		Timespan:   models.Minute,
		From:       models.Millis(time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC)),
		To:         models.Millis(time.Date(2023, 3, 9, 0, 0, 0, 0, time.UTC)),
	}.WithOrder(models.Desc).WithLimit(50000).WithAdjusted(false)

	// make request
	iter := c.ListAggs(context.Background(), params, models.WithTrace(true))

	// do something with the result
	for iter.Next() {
		log.Print(iter.Item())
	}
	if iter.Err() != nil {
		log.Fatal(iter.Err())
	}

}
```

You can dump the url and headers if you add `models.WithTrace(true)` to the request on here `iter := c.ListAggs(context.Background(), params, models.WithTrace(true))`. This is pretty helpful when you want to debug things just by adding a little code.

And the output will look something like this:

```
Request URL: /v2/aggs/ticker/O:SPY251219C00650000/range/5/minute/1672531200000/1678320000000?adjusted=false&limit=50000&sort=desc
Request Headers: map[Accept-Encoding:[gzip] Authorization:[REDACTED] User-Agent:[Polygon.io GoClient/v1.14.1]]
Response Headers: map[Content-Encoding:[gzip] Content-Length:[1720] Content-Type:[application/json] Date:[Wed, 23 Aug 2023 05:41:06 GMT] Server:[nginx/1.19.2] Strict-Transport-Security:[max-age=15724800; includeSubDomains] Vary:[Accept-Encoding] X-Request-Id:[22ca1dd9571df8d0d740b31f71eeed17]]
2023/08/22 22:41:06 { 2.28 2.45 2.28 2 2.45 {0 63813903000 0x104a31420} 2 2.365 false}
2023/08/22 22:41:06 { 2.52 2.52 2.52 1 2.52 {0 63813884100 0x104a31420} 1 2.52 false}
2023/08/22 22:41:06 { 2.55 2.6 2.55 2 2.6 {0 63813819000 0x104a31420} 2 2.575 false}
2023/08/22 22:41:06 { 2.65 2.65 2.65 1 2.65 {0 63813818700 0x104a31420} 1 2.65 false}
2023/08/22 22:41:06 { 2.65 2.65 2.5 2 2.5 {0 63813817800 0x104a31420} 2 2.575 false}
...
2023/08/22 22:41:06 { 6.38 6.38 6.38 1 6.38 {0 63809065200 0x104a31420} 1 6.38 false}
2023/08/22 22:41:06 { 3.9 3.9 3.9 1 3.9 {0 63808961700 0x104a31420} 3 3.9 false}
2023/08/22 22:41:06 { 3.89 3.89 3.89 1 3.89 {0 63808890900 0x104a31420} 1 3.89 false}
2023/08/22 22:41:06 { 4.08 4.08 4.08 1 4.08 {0 63808890600 0x104a31420} 1 4.08 false}
2023/08/22 22:41:06 { 2.8 3.71 2.8 2 3.71 {0 63808614900 0x104a31420} 2 3.255 false}
```

I don't think this is a bug in that the API can accept both date formats either YYYY-MM-DD to unixtime. Let me know if this makes sense. Also, thanks for the detailed report. I know that took some time putting together.
