### ISSUE TITLE
Improve JSON performance by setting or allowing a compatible parser to be set on resty

### ISSUE THREAD

**Issue by weirdninja** [polygon-io/client-go#353]
The standard json parsing library is reasonably slow in comparison to some other alternatives. The Resty folks describe in https://github.com/go-resty/resty/issues/76#issuecomment-314015250 the few lines needed to change Resty's json parser to something else.

The project could settle on jsoniter or perhaps something else, but in any case, we should be allowed to override this in case something better comes up to be future proof.

**Comment by justinpolygon** [comment]
Hey @weirdninja, have you written anything here or patched your client for this? Just wondering what your use-case is? I know for the websocket we support raw message types where you can roll your own parser. Maybe we could use something similar and just return the raw messages via a flag and then you roll your own parser via whatever library you want.

**Comment by weirdninja** [comment]
Hi!

I noticed that, for the REST calls, I could set the parser directly on resty since the client is exposed.

So something like:
```
client := polygon.New("token")
client.Client.HTTP.SetJSONMarshaler(jsoniter.Marshal)
client.Client.HTTP.SetJSONUnmarshaler(jsoniter.Unmarshal)
```
worked fine for the rest calls.

I have a task to look into a way to implement jsoniter for websockets. I will eventually get to it. Are there any pointers you could provide?

**Comment by weirdninja** [comment]
About the use case: a pperf analysis of our client usage showed a significant amount of time parsing json due to the size of the option chains. This implementation did boost things by some 10-20%. I don't have the numbers handy, but it was significant.
