### ISSUE TITLE
nit: outdated tutorial

### ISSUE THREAD

**Issue by rrshaban** [polygon-io/client-go#418]
**Describe the bug**
<https://polygon.io/blog/go-stock-market-data>

```go get github.com/polygon-io/client-go```

running that command today delivers

```
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

may be replaced with 
```
go install github.com/polygon-io/client-go@latest
```

**Comment by justinpolygon** [comment]
Hey @rrshaban, yeah I'll fix that. Thanks for pointing it out!

**Comment by justinpolygon** [comment]
Fixed -- thanks for reporting. Deploying is going out now.
