### ISSUE TITLE
nit: outdated link in the docs

### ISSUE THREAD

**Issue by rrshaban** [polygon-io/client-go#419]
<https://polygon.io/blog/go-stock-market-data>
"From here, interacting with the Polygon.io API's is easy. We have over 50 [example code snippet](https://github.com/polygon-io/client-go/tree/master/rest/example?ref=polygon.io) to help you get started, here's one on how to get aggregate bars for a stock over a given date range ([code here](https://github.com/polygon-io/client-go/blob/master/rest/example/stocks-aggregates-bars/main.go?ref=polygon.io)):"
shall point instead to <https://github.com/polygon-io/client-go/blob/master/rest/example/main.go> ?

**Comment by justinpolygon** [comment]
Thanks @rrshaban. I'll fix. Sorry about that.

**Comment by justinpolygon** [comment]
Fixed -- thanks for reporting. Deploying is going out now.
