### ISSUE TITLE
Regarding your v1 branch.

### ISSUE THREAD

**Issue by andersc** [polygon-io/client-go#49]
Hi,
 
We started writing a polygon.io golang package but, noticed you are producing one yourselves (The v1 branch), that's great!
  
We want to use your version over ours and we will stop developing our package. However, if it's of interest to you, we open-source our implementation for you to look at and if you want to cherry-pick anything from there please do so. I do understand our design-patterns look different, so see this as a friendly gesture. Then when you release your or earlier, we will remove ours from being public on github.
 
Our implementation (MIT-License) can be found here ->
 
https://github.com/tickup-se/go-polygon

**Comment by morningvera** [comment]
Hey @andersc, thanks for the offer! I'll take a look at your implementation when I get a chance. We're actually going to merge that branch and release `v0.1.0` very soon. It's not 100% stable yet but you're welcome to try it out (feedback welcome). Currently, we just support our REST API but the Websocket API is coming soon.
