### ISSUE TITLE
type *polygon.PolygonClient has no field or method ListTickers

### ISSUE THREAD

**Issue by aggregated** [polygon-io/client-go#95]
**Describe the bug**

Upon installing and initializing the client as proposed in README.md, it is not possible to use the client as the documentation suggests. The returned pointer does not seem to implement the client functionality.

**To Reproduce**

1. Create a fresh go module using `go mod init`
2. Add client using `go get github.com/polygon-io/client-go`
3. Create a simple program as suggested by the documentation in README.md:

```
package main

import (
	"context"
	polygon "github.com/polygon-io/client-go/rest"
	"github.com/polygon-io/client-go/rest/models"
)

func main() {
	c := polygon.New("{REDACTED}")
	res, err := c.ListTickers(context.Background())
}
```

5. Execute the program 

```
> go run ptest.go                            
# command-line-arguments
./ptest.go:11:16: c.ListTickers undefined (type *polygon.PolygonClient has no field or method ListTickers)
```

**Expected behavior**

The client module should implement the client functions.

**Additional context**

```
> go version
go version go1.18.1 darwin/arm64
```

**Comment by morningvera** [comment]
Hey @aggregated, you're looking at the latest readme but I'm assuming you're using the `v0.3.0` tag. Take a look at that tag's readme for help: https://github.com/polygon-io/client-go/tree/v0.3.0.

We're still in pre-release and will be making breaking changes as needed (use at your own risk). The latest readme reflects the state of things in `v0.4.0` which will be released tomorrow. Going to close this since it's not actually a bug but thanks for submitting the issue!

**Comment by aggregated** [comment]
Hello @morningvera, 

thank you for the clarification, my mistake.

We're currently implementing a new data collector and would love to use this API client. The other option would be writing one, which is not favorable.

I understand the pre-release nature of this repository, but *if* you were to use it (and accepting you would most likely have to revise again later), could you please point me to the commit you would use?

**Comment by morningvera** [comment]
@aggregated I'd suggest using `v0.4.0` as soon as we release it tomorrow! The REST client is approaching stability and will be less likely to change after tomorrow's release. It's also going to include a WebSocket client (pretty full featured at this point but maybe not totally stable).
